// s-gol/src/grid/grid-display.svelte
<script>
  import Grid from '../../../common/grid';
  import { isPausedStore, widthStore, heightStore, randomizeEventsSubject } from './grid-store'

  export let width = 1;
  export let height = 1;

  let isPaused = false;

  let displayedGrid = new Grid(width, height);
  displayedGrid.randomize();

  isPausedStore.subscribe(is => {
    isPaused = is;
  });

  function updateDisplayedGrid(grid) {
    displayedGrid = grid;
  }

  function onClickCell() {
    const row = parseInt(this.getAttribute('datarow'));
    const col = parseInt(this.getAttribute('datacol'));

    displayedGrid.cells[row][col] = !displayedGrid.cells[row][col];
  }

  widthStore.subscribe(newWidth => {
    width = newWidth;
    updateDisplayedGrid(displayedGrid.cloneGridWithNewDimensions(width, height));
  });

  heightStore.subscribe(newHeight => {
    height = newHeight;
    updateDisplayedGrid(displayedGrid.cloneGridWithNewDimensions(width, height));
  });

  randomizeEventsSubject.subscribe(() => {
    const nextrid = new Grid(width, height);
    nextrid.randomize();
    updateDisplayedGrid(nextrid);
  });

  window.setInterval(() => {
    if (!isPaused) {
      updateDisplayedGrid(displayedGrid.nextGrid());
    }
  }, 10);

</script>

<style>
  .row {
    display: inline-block;
  }

  .cell {
    padding: 2px;
  }

  .cell-alive {
    background-color: #dddddd;
  }

  .cell-dead {
    background-color: #333333;
  }
</style>

<div>
  {#each displayedGrid.cells as row, cRow}
  <div class="row">
    {#each row as cell, cCol}
    <div class="cell {cell ? 'cell-alive' : 'cell-dead'}" on:click={onClickCell} dataRow={cRow} dataCol={cCol}>
    </div>
    {/each}
  </div>
  {/each}
</div>

// a-gol/src/app/grid-display/grid-display.component.ts
import { Component, Input, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { ReplaySubject } from 'rxjs';
import Grid from '../../../../common/grid';
import { INITIAL_HEIGHT, INITIAL_IS_PAUSED, INITIAL_WIDTH } from '../controls/controls.component';

@Component({
  selector: 'app-grid-display',
  templateUrl: './grid-display.component.html',
  styleUrls: ['./grid-display.component.scss'],
})
export class GridDisplayComponent implements OnChanges, OnInit {

  @Input()
  width: number;

  @Input()
  height: number;

  @Input()
  isPaused: boolean;

  @Input()
  randomizeNotifier: ReplaySubject<any>;

  displayedGrid: Grid;

  constructor() {
  }

  updateDisplayedGrid(grid: Grid) {
    this.displayedGrid = grid;
  }

  onClickCell(row: number, col: number) {
    this.displayedGrid.cells[row][col] = !this.displayedGrid.cells[row][col];
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.displayedGrid) {
      return;
    }

    if (changes.width) {
      const newWidth = changes.width.currentValue;
      const nextGrid = this.displayedGrid.cloneGridWithNewDimensions(newWidth, this.height);
      this.updateDisplayedGrid(nextGrid);
    }

    if (changes.height) {
      const newHeight = changes.height.currentValue;
      const nextGrid = this.displayedGrid.cloneGridWithNewDimensions(this.width, newHeight);
      this.updateDisplayedGrid(nextGrid);
    }
  }

  ngOnInit(): void {
    this.isPaused = INITIAL_IS_PAUSED;
    this.width = INITIAL_WIDTH;
    this.height = INITIAL_HEIGHT;
    this.displayedGrid = new Grid(this.width, this.height);
    this.displayedGrid.randomize();

    window.setInterval(() => {
      if (!this.isPaused) {
        this.updateDisplayedGrid(this.displayedGrid.nextGrid());
      }
    }, 50);

    this.randomizeNotifier.subscribe(() => {
      const nextGrid = new Grid(this.width, this.height);
      nextGrid.randomize();
      this.updateDisplayedGrid(nextGrid);
    });
  }


}

<div *ngIf="displayedGrid">
  <div class="row" *ngFor="let row of displayedGrid.cells; let cRow = index; trackBy: index">
    <div *ngFor="let cell of row; let cCol = index; trackBy: index + cRow"
         [ngClass]="{'cell': true, 'cell-alive': cell, 'cell-dead': !cell}"
         (click)="onClickCell(cRow, cCol)">
    </div>
  </div>
</div>
