// a-gol/src/app/controls/controls.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

export const INITIAL_WIDTH = 20;
export const INITIAL_HEIGHT = 10;
export const INITIAL_IS_PAUSED = true;

@Component({
  selector: 'app-controls',
  templateUrl: './controls.component.html',
  styleUrls: ['./controls.component.scss'],
})
export class ControlsComponent {
  @Output()
  randomizeRequest = new EventEmitter();

  @Output()
  widthRequest = new EventEmitter<number>();

  @Output()
  heightRequest = new EventEmitter<number>();

  @Output()
  isPausedRequest = new EventEmitter<boolean>();

  isPaused = INITIAL_IS_PAUSED;
  width = INITIAL_WIDTH;
  height = INITIAL_HEIGHT;

  onClickPause() {
    this.isPaused = !this.isPaused;
    this.isPausedRequest.emit(this.isPaused);
  }

  onClickRandomize() {
    this.randomizeRequest.emit();
  }

  onChangeWidth() {
    this.widthRequest.emit(this.width);
  }

  onChangeHeight() {
    this.heightRequest.emit(this.height);
  }
}

<div class="controls-bar">
  <fieldset>
    <label for="width-input">Width : {{width}}</label>
    <input id="width-input" type="range" [(ngModel)]="width" (input)="onChangeWidth()"
           min="9" max="450" step="1">
  </fieldset>

  <fieldset>
    <label for="height-input">Height : {{height}}</label>
    <input id="height-input" type="range" [(ngModel)]="height" (input)="onChangeHeight()"
           min="9" max="180" step="1">
  </fieldset>

  <button type="button" (click)="onClickRandomize()">
    Randomize
  </button>

  <button type="button" (click)="onClickPause()">
    {{isPaused ? "resume": "stop"}}
  </button>

  <span>Grid size : {{width * height}} cells.</span>
</div>

// s-gol/src/controls/controls.svelte
<script>
  import { get } from 'svelte/store';
  import { isPausedStore, widthStore, heightStore, randomizeEventsSubject } from '../grid/grid-store';

  function onClickPause() {
    isPausedStore.update(is => !is)
  }

  function onClickRandomize() {
    randomizeEventsSubject.next();
  }

  function onChangeWidth() {
    widthStore.set(width);
  }

  function onChangeHeight() {
    heightStore.set(height);
  }

  let isPaused = false;
  let width = get(widthStore);
  let height = get(heightStore);

  isPausedStore.subscribe(is => {
    isPaused = is;
  });
</script>

<style>
  .controls-bar {
    display: inline-block;
  }

  fieldset {
    display: inline-block;
  }
</style>

<div class="controls-bar">
  <fieldset>
    <label for="width-input">Width : {width}</label>
    <input id="width-input" type="range" bind:value={width} on:input={onChangeWidth}
           min="9" max="450" step="1">
  </fieldset>

  <fieldset>
    <label for="height-input">Height : {height}</label>
    <input id="height-input" type="range" bind:value={height} on:input={onChangeHeight}
           min="9" max="180" step="1">
  </fieldset>

  <button type="button" on:click={onClickRandomize}>
    Randomize
  </button>

  <button type="button" on:click={onClickPause}>
    {isPaused ? "resume": "stop"}
  </button>

  <span>Grid size : {width * height} cells.</span>
</div>
