// s-gol/src/App.svelte
<script>
  import Grid from './grid/grid-display.svelte';
  import Controls from './controls/controls.svelte';
	export let projectType;

	const toto = Grid || Controls;
</script>

<style>
  .title-container {
    display: inline-block;
  }

	h3 {
		color: purple;
	}
</style>

<div class="app">
  <div class="title-container">
    <h1>Game Of Life ! </h1>
    <h3><i>{projectType} version</i></h3>
  </div>

  <Controls></Controls>

  <Grid></Grid>
</div>

// a-gol/src/app/app.component.ts
import { Component } from '@angular/core';
import { ReplaySubject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  projectType = 'Angular';

  width: number;
  height: number;
  isPaused: boolean;

  randomizeNotifier = new ReplaySubject();

  onWidthMessage(width: number) {
    this.width = width;
  }

  onHeightMessage(height: number) {
    this.height = height;
  }

  onIsPausedMessage(isPaused: boolean) {
    this.isPaused = isPaused;
  }

  onRandomizeMessage() {
    this.randomizeNotifier.next();
  }
}

<div class="app">
  <div class="title-container">
    <h1>Game Of Life ! </h1>
    <h3><i>{{projectType}} version</i></h3>
  </div>

  <app-controls (widthRequest)="onWidthMessage($event)"
                (heightRequest)="onHeightMessage($event)"
                (isPausedRequest)="onIsPausedMessage($event)"
                (randomizeRequest)="onRandomizeMessage()">

  </app-controls>

  <app-grid-display [width]="width" [height]="height" [isPaused]="isPaused" [randomizeNotifier]="randomizeNotifier">
  </app-grid-display>
</div>
